---
- name: "Setup Server - Node Js"
  hosts: control
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  pre_tasks:
    - pause: seconds=60
    - name: "update apt packages"
      become: true
      apt:
        update_cache: yes
    - name: Check if python is already latest
      command: python3 --version
      register: python_version_result
      failed_when: "{{ python_version_result.stdout | replace('Python ', '') | version_compare(python_version, '>=') }}"
    - name: Install prerequisites
      apt: name=python-software-properties state=present
      become: true
    - name: Add deadsnakes repo
      apt_repository: repo="ppa:deadsnakes/ppa"
      become: true
    - name: Install python
      apt: name="python{{ python_version }}-dev" state=present
      become: true
  roles:
   - setup